name = "test-dashboard"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-dashboard_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-dashboard.wasm"
command = "npm run build:release"
